name: deploy dotnet web app in IIS server

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: iis-test-runner
    steps:

      - name: Checkout of the Code
        uses: actions/checkout@v3

      - name: Install .NET Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.300'

      - name: Verify the .NET Installation
        run: dotnet --version

      - name: Build the Application with .NET
        run: dotnet build --configuration Release

      - name: Publish the Deployment Package in public folder
        run: dotnet publish -c Release -o public

  deploy:
    runs-on: iis-test-runner
    steps:
      - name: Create a Artifact using from the public folder
        uses: actions/upload-artifact@v3
        with:
          name: public folder
          path: public

      - name: Copy folder from work directory to wwwroot
        #run: xcopy /E /C /R /Y .\public\* C:\inetpub\wwwroot\
        run: |
          iisreset /stop
          Copy-Item ./public/* C:/inetpub/wwwroot/ -Recurse -Force
          iisreset /start
          
  JfrogArtifact-Upload:
      runs-on: iis-test-runner
      needs: deploy
      steps:
      - name: run jfrog cli in VM
        run: powershell "Start-Process -Wait -Verb RunAs powershell '-NoProfile iwr https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/[RELEASE]/jfrog-cli-windows-amd64/jf.exe -OutFile $env:SYSTEMROOT\system32\jf.exe'" ; jf setup
      
      - name: check Jfrog version & config
        run:  jf -v
  
      
        

               
